import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { createSession } from "@/lib/session";

/**
 * GET /api/auth/line-login?token=XXX
 *
 * Verifies the one-time token generated by the LINE webhook and creates
 * a web session, then redirects to the dashboard (or pending invite group).
 */
export async function GET(request: NextRequest) {
    const token = request.nextUrl.searchParams.get("token");
    if (!token) {
        return Response.redirect(new URL("/login?error=missing_token", request.url));
    }

    const user = await prisma.user.findUnique({ where: { webLoginToken: token } });

    if (
        !user ||
        !user.webLoginExpiry ||
        user.webLoginExpiry < new Date()
    ) {
        return Response.redirect(new URL("/login?error=invalid_token", request.url));
    }

    // Consume the token (one-time use)
    await prisma.user.update({
        where: { id: user.id },
        data: { webLoginToken: null, webLoginExpiry: null },
    });

    await createSession({
        userId: user.id,
        email: user.email ?? "",
        name: user.name,
    });

    // Check for pending invite cookie → auto-join and redirect to group
    const pendingInvite = request.cookies.get("pendingInvite")?.value;
    if (pendingInvite) {
        const group = await prisma.group.findUnique({
            where: { inviteCode: pendingInvite.toUpperCase() },
        });
        if (group) {
            const existing = await prisma.groupMember.findUnique({
                where: { userId_groupId: { userId: user.id, groupId: group.id } },
            });
            if (!existing) {
                await prisma.groupMember.create({
                    data: { userId: user.id, groupId: group.id, role: "member" },
                });
            }
            const res = Response.redirect(new URL(`/groups/${group.id}`, request.url));
            res.headers.append(
                "Set-Cookie",
                "pendingInvite=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax"
            );
            return res;
        }
    }

    return Response.redirect(new URL("/dashboard", request.url));
}
